# Autogenerated wrapper script for GoogleCodeSearch_jll for x86_64-linux-gnu
export cindex, csearch

JLLWrappers.@generate_wrapper_header("GoogleCodeSearch")
JLLWrappers.@declare_executable_product(cindex)
JLLWrappers.@declare_executable_product(csearch)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        cindex,
        "bin/cindex",
    )

    JLLWrappers.@init_executable_product(
        csearch,
        "bin/csearch",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
